name: source_transformer
author: Dart Team <misc@dartlang.org>
version: 0.1.0
description: Patterns for easily re-writing source code
homepage: https://www.github.com/google/source_transformer.dart

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  analyzer: '>=0.29.1 <0.30.0'
  collection: '^1.11.0'
  meta: '^1.0.3'
  quiver: '>=0.22.0 <0.30.0'
  source_span: '^1.0.0'

dev_dependencies:
  test: '^0.12.17'
